"-": &dockerbuild
  steps:
    - checkout

    # Which version of ruby?
    - run:
        name: Which ruby?
        command: ruby --version | tee ruby-version-for-ci.txt

    # Which version of bundler?
    - run:
        name: Which bundler?
        command: bundle -v

    - run:
        name: Install Crystal
        command: >-
          sudo apt-get update &&
          sudo apt-get install apt-transport-https ca-certificates &&
          curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash &&
          curl -sL "https://keybase.io/crystal/pgp_keys.asc" | sudo apt-key add - &&
          echo "deb https://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list &&
          sudo apt-get update &&
          sudo apt-get -y install crystal &&
          crystal --version

    # Restore bundle cache
    - restore_cache:
        keys:
          - bundler-packages-v2-{{ checksum "ruby-version-for-ci.txt" }}-{{ checksum "ruby_crystal_codemod.gemspec" }}

    - run:
        name: Bundle Install
        command: bundle check || bundle install

    - run:
        name: Compile ./util/post_process tool
        command: ./bin/compile_post_process

    - run:
        name: Run rspec
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress
    - run:
        name: Run RuboCop
        command: |
          bundle exec rake rubocop
    - run:
        name: Run Rufo
        command: |
          bundle exec rufo -c lib/ spec/lib/

    # Store bundle cache
    - save_cache:
        key: bundler-packages-v2-{{ checksum "ruby-version-for-ci.txt" }}-{{ checksum "ruby_crystal_codemod.gemspec" }}
        paths:
          - vendor/bundle
          - Gemfile.lock

    # Save test results for timing analysis
    - store_test_results:
        path: test_results


version: 2
jobs:
  build-2-6-5:
    <<: *dockerbuild
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: /home/circleci/project/vendor/bundle
  build-2-4-5:
    <<: *dockerbuild
    docker:
      - image: circleci/ruby:2.4.5
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          BUNDLE_PATH: vendor/bundle
workflows:
  version: 2
  test:
    jobs:
      - build-2-6-5
      - build-2-4-5
